# Generated by Django 3.2.10 on 2022-02-28 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('professional_training', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Profile pic (leave empty for default pic)')),
                ('tk', models.CharField(default=uuid.UUID('5301dbf7-0017-4c5c-b7a7-897ef48daea4'), max_length=255, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
