# Generated by Django 3.2.10 on 2022-02-28 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_tk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tk',
            field=models.CharField(default=uuid.UUID('3ed3088f-5c10-42eb-b693-0a9198b0e63d'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
